services:
  - type: web
    name: movierec-api
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: UPSTASH_REDIS_URL
        sync: false
      - key: UPSTASH_REDIS_TOKEN
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: HF_REPO_ID
        value: your-username/movierec-artifacts
    healthCheckPath: /health
